### ISSUE TITLE
BitBucket: A third option to wheel scroll direction

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/MouseTweaks#1]
Old issue link: https://bitbucket.org/YaLTeR/mouse-tweaks/issues/10/a-third-option-to-wheel-scroll-direction

**Comment by 4rz0** [comment]
Was about to write this issue.
I'd love this option as well.

**Comment by YaLTeR** [comment]
I added an "Inventory position aware" scroll direction which should behave as described in the issue.
