### ISSUE TITLE
Time stamp in config

### ISSUE THREAD

**Issue by 016Nojr** [YaLTeR/MouseTweaks#10]
Can you remove this? I dont see why it should be in there?

**Comment by YaLTeR** [comment]
Not at home so can't check myself; could you show me what you're talking about? I don't think I explicitly store any timestamps into the config.

**Comment by 016Nojr** [comment]
![timestamp](https://user-images.githubusercontent.com/8192699/43830286-3b3393a4-9b01-11e8-92d5-b5c468dbe663.PNG)

**Comment by YaLTeR** [comment]
Yeah, that's the default behavior of `java.util.Properties`, I don't see an easy way of disabling it.

**Comment by LatvianModder** [comment]
Why arent you using forge's Configuration?

**Comment by YaLTeR** [comment]
Well, at least because MT doesn't require Forge: it can be loaded with just LiteLoader. Since it's such a simple mod, I'd like to keep it this way.

**Comment by LatvianModder** [comment]
then if you dont use comments, maybe you can use json as config?

**Comment by YaLTeR** [comment]
Why though? The current system using Properties is about as simple as it can possibly get from both the code and the user friendliness perspective. I don't see how this timestamp comment is such a big issue to change anything.

**Comment by LatvianModder** [comment]
I think the issue was that we use git for modpack dev and this changing every time counts as git change

**Comment by YaLTeR** [comment]
Hmm I see. I'll mark this as enhancement then and see what I can do next time I update the mod. Maybe not save the file unless there's a change or not using Properties altogether.

**Comment by LatvianModder** [comment]
This file is supposed to be user/client only, not modpack? You could move it to `local/mousetweaks.properties`

**Comment by YaLTeR** [comment]
It is useful for modpacks: certain mods add their own wheel tweak functionality in which case the one in Mouse Tweaks needs to be manually disabled (by the modpack authors) to avoid conflicts. Also I've never seen that kind of folder structure.

**Comment by YaLTeR** [comment]
In the latest version I'm writing the config file manually, without any timestamps and with settings in a determined order.
