### ISSUE TITLE
1.17.1 replay mod + mouse tweaks 

### ISSUE THREAD

**Issue by dangereffect** [YaLTeR/MouseTweaks#101]
mouse tweaks stopped working after downloading replay mod, i saw that you answered to this issue but i cant download new structure form this link. can you help me? 
![image](https://user-images.githubusercontent.com/128088325/225725602-41a9bbef-76c6-4c49-82c9-8aac68427edd.png)

**Comment by YaLTeR** [comment]
I'm afraid I only fixed it for Minecraft 1.18 and above, there's no 1.17.1 build with the fix unfortunately.

**Comment by dangereffect** [comment]
> I'm afraid I only fixed it for Minecraft 1.18 and above, there's no 1.17.1 build with the fix unfortunately.

oh okay :/ maybe you have this link for 1.18?

**Comment by YaLTeR** [comment]
You can grab the latest 1.18 version from here: https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks/files
