### ISSUE TITLE
mod not loading

### ISSUE THREAD

**Issue by huglikestoplay** [YaLTeR/MouseTweaks#103]
i downloaded MouseTweaks and put in my mod folder but when i launch the game the mod is not there like i did not download it even though i did

**Comment by YaLTeR** [comment]
Did you download the right version? There are separate files for Fabric and Forge.

**Comment by huglikestoplay** [comment]
i have these mods installed and yes i downloaded the fabric version
![afbeelding_2023-03-25_210919335](https://user-images.githubusercontent.com/128909396/227739191-2f4ac26b-689c-4d3b-a9d4-de5249dbe7bc.png)

**Comment by YaLTeR** [comment]
What makes you think it's not working?

**Comment by huglikestoplay** [comment]
i cant find any of the controls for it and when i try one of the features i does not work i used it before on a diffrent computer and there it worked just fine

**Comment by YaLTeR** [comment]
Could you install mod menu and check if mouse tweaks shows up, and if in its settings things are enabled? https://www.curseforge.com/minecraft/mc-mods/modmenu

**Comment by huglikestoplay** [comment]
these are the options i see
![afbeelding_2023-03-25_213919369](https://user-images.githubusercontent.com/128909396/227740525-d0336ccd-9a71-42af-87df-09ccd8479bd6.png)

**Comment by YaLTeR** [comment]
Yeah, that looks good. Not sure, the mod should work. Try RMB dragging with item in a chest. If it doesn't then maybe there's some incompatibility with another mod; you could try with just mouse tweaks and no other mods installed.

**Comment by huglikestoplay** [comment]
![afbeelding_2023-03-25_214340406](https://user-images.githubusercontent.com/128909396/227740688-e4db4665-395b-4402-9891-1deaf973b69b.png)
now minecraft wont start up at all

**Comment by YaLTeR** [comment]
Oh, don't remove the fabric API, it's required for most fabric mods.

**Comment by huglikestoplay** [comment]
nope even with no mods installed it still does not work

**Comment by YaLTeR** [comment]
Well, not sure, should work

**Comment by huglikestoplay** [comment]
i guess i just have to hope i get my other computer back
