### ISSUE TITLE
cross-compatibility for DANK Storage

### ISSUE THREAD

**Issue by koalalord9999** [YaLTeR/MouseTweaks#104]
https://github.com/Tfarcenim/Dank-Storage/issues/184#issue-1473628879

This is a big issue for DANK users. it deletes everything in there.

**Comment by YaLTeR** [comment]
Mouse Tweaks does not have sorting functionality. It's some other mod.

**Comment by koalalord9999** [comment]
My bad, probably inventory tweaks was just using the mod the guy questioned in the post lol
