### ISSUE TITLE
RMB Without Item not working

### ISSUE THREAD

**Issue by jackk225** [YaLTeR/MouseTweaks#106]
I'm using version 2.22 in Fabric 1.19.2 and most of the tweaks work, but the RMB without item tweak doesn't. The config file does have "LMBTweakWithoutItem=1"

**Comment by jackk225** [comment]
Scratch that, none of the tweaks are working. I may have an incompatible mod, not sure how to attach a modlist. Sorry for taking your time!

**Comment by YaLTeR** [comment]
Hey, yeah, try with just mouse tweaks and no other mods. As for incompatible mods it can be something like simple inventory sorter or I think Easy shulker boxes recently?
