### ISSUE TITLE
Mod does not respect inventory permissions

### ISSUE THREAD

**Issue by Brycey92** [YaLTeR/MouseTweaks#11]
When opening a GUI which you would not typically be able to remove items from or add items to (such as a Sponge plugin's chest-style menu), this mod allows you to freely shift-click, space-click, alt-click, etc. The items are moved or dropped as they normally would be if you had a chest open.

This issue means the mod is not suitable for use on many servers.

**Comment by YaLTeR** [comment]
Mouse Tweaks doesn't have any special "shift-click", "space-click" or "alt-click" functionality, only dragging and scrolling. Also it's entirely client-side and works by actually emitting regular clicks on the inventory, which means issues like this one are either impossible or on the mod-providing-the-inventory's side.

Judging by your description, it's most likely an issue with some other inventory-related mod.

**Comment by Brycey92** [comment]
My apologies, I just did some testing and realized I mistook the features in question causing the bugs as being from your mod. The actual culprit is the Inventory Tweaks mod, when used on both client and server. Thanks for your help, and have a great weekend!
