### ISSUE TITLE
plz support Minecraft 1.20 with Fabric

### ISSUE THREAD

**Issue by JingHai-Lingyun** [YaLTeR/MouseTweaks#111]
i'm making a client for my server，but i dont find any version for mc 1.20 fabric
only this unknow version mod（it says just api not update and tell me wait)
![image](https://github.com/YaLTeR/MouseTweaks/assets/109946426/a6d0f6c7-f843-4729-9f0f-977cd42e5847)

**Comment by YaLTeR** [comment]
Updated.

https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks/files?version=1.20

https://modrinth.com/mod/mouse-tweaks/versions

**Comment by JingHai-Lingyun** [comment]
tks.
