### ISSUE TITLE
Use 'fabric-api' mod ID in fabric.mod.json 

### ISSUE THREAD

**Issue by Poopooracoocoo** [YaLTeR/MouseTweaks#116]
Users may be confused when they see that it depends on `fabric`, not knowing that it's referring to the Fabric API. 

>As of Minecraft 1.19.2, Fabric API's mod ID has changed from `fabric` to `fabric-api`. When backporting from 1.19.2 to earlier versions, you must alter the `depends` section of your `fabric.mod.json` to expect `fabric`.

From https://fabricmc.net/wiki/tutorial:setup#mod_setup

---

You should also add the Fabric API dependency for releases on CF and MR so that launchers can download it automatically.

**Comment by YaLTeR** [comment]
Oh okay. Want to make a pull request?

> You should also add the Fabric API dependency for releases on CF and MR so that launchers can download it automatically.

Yea I already do it on modrinth.
