### ISSUE TITLE
Curios/aether/l2's library interaction

### ISSUE THREAD

**Issue by DaPuffer** [YaLTeR/MouseTweaks#118]
Played 2 ftb modpacks(FTB:Unstable:1.20 and direwolf20 1.20) in both of them l2's library and curios is installed and in direwolf there is also the aether mod. If you sort any of the mod's inventories(be it the aether equip slots,curios slots or the l2's menu slots(just both combined) it deletes some items. Could be an issue of l2's library or a modpack compat issue with something

**Comment by YaLTeR** [comment]
Mouse Tweaks does not have item sorting functionality, it is some other mod. Probably "Simple Inventory Sorter".
