### ISSUE TITLE
Lag Spikes when opening inventories

### ISSUE THREAD

**Issue by Sekwah** [YaLTeR/MouseTweaks#12]
**ModPack**: Stoneblock
**Problem**: Lag Spikes (or Game Freezes) when opening inventories, doesn't matter if it's a modded or vanilla inventory, it will lag.

[Video](https://www.youtube.com/watch?v=f21uwABA3nU&feature=youtu.be)

I don't know if it's a problem with another mod in the pack, but disabling this one solves the problem. In Stoneblock's git they suggested me to report it here.

**Comment by YaLTeR** [comment]
Thank you very much for the report and the video!

Possibly related to #9? Could you try reproducing it on a clean build with the same Forge/LiteLoader and just Mouse Tweaks?

**Comment by Sekwah** [comment]
LiteLoader is not installed, just Forge, so it's not related to #9.

I tried a clean installation with Forge-14.23.4.2760 (also tried the latest and it's the same) and the latest release of mouse tweaks and [it's still happening](https://youtu.be/8E4fhfcHCGA).

PC Specs just in case:
I5 6600k @3.6Ghz
16GB RAM (8 allocated for the game)
GTX 970
W10

**Comment by YaLTeR** [comment]
I will try reproducing it tomorrow.

**Comment by YaLTeR** [comment]
Hmm, can't reproduce it in this case either. I have a slight suspicion of what could be causing it though. What hard drive is your .minecraft folder on? Like the model.

**Comment by Sekwah** [comment]
Currently installed in a WD Blue (1TB) @7200RPM (model WD10EZEX). I doubt that's the problem since a friend have the same disk and he doesn't have these problems.

I decided to test (a clean install, forge+mousetweaks) on my SSD (Samsung 850 Evo 256GB) and the problem was still there. It may be related to some game config or forge config?

**Comment by YaLTeR** [comment]
Hmm. The only questionable thing that MT does upon opening inventories is reading and writing its config file (which I intend to change in the next update).

I made a [temporary build](https://0x0.st/sgm_.jar) which does not read or write the config file upon opening inventories, could you try that?

**Comment by YaLTeR** [comment]
Great to hear!

Yeah, I've absolutely no clue why it occurs only for some people.

Could you please also test [this new temporary build](https://0x0.st/sgmy.jar) where it still reads the config file every time an inventory is opened, but doesn't write it back?

**Comment by Sekwah** [comment]
That version also works perfectly in a clean install.

**Comment by YaLTeR** [comment]
Alright, awesome. I'll try to get an update out in a few days then.

**Comment by YaLTeR** [comment]
Sorry for taking so long! I'll release new version today.
