### ISSUE TITLE
[1.19.2][forge]Item duplication when installed with Create

### ISSUE THREAD

**Issue by FCWYzzr** [YaLTeR/MouseTweaks#120]
# what happened
MT treats Create item filter GUI as inventory, causes possibility for player to duplicate any item
# detail
see [the issue i submitted to Create](https://github.com/Creators-of-Create/Create/issues/5746)

**Comment by YaLTeR** [comment]
Mouse Tweaks is clientside-only. If there's any way you can dupe items with it, then you can do the same without Mouse Tweaks, so it's not a MT issue.

**Comment by YaLTeR** [comment]
Try with Mouse Tweaks removed. It might be some other mod.

**Comment by FCWYzzr** [comment]
Yes U R right, Im trying to locate the problem Mod

**Comment by FCWYzzr** [comment]
Ive tested several mods, and Inventory Sorter is to blame. Sorry for this wrong issue
