### ISSUE TITLE
Crashes minecraft when scrolling

### ISSUE THREAD

**Issue by calebmeyer** [YaLTeR/MouseTweaks#123]
## Error message
java.lang.NoSuchMethodError: 'double net.minecraftforge.client.event.ScreenEvent$MouseScrolled$Post.getScrollDelta()'

## Versions
Minecraft: 1.20.4
Mouse Tweaks: 2.25
Forge: 49.0.19
Prism Launcher: 8.0
Fedora: 39

Note: I ensured that I reproduced this with no other mods so that it wasn't an interaction causing it

## Steps to reproduce
- Create a new single player world
- Open your inventory
- Scroll over any space

## Error logs
https://gist.github.com/calebmeyer/30459b778191e4e487f98ab69d5a999f

**Comment by YaLTeR** [comment]
You're running Mouse Tweaks for Forge 1.20 on 1.20.4, it needs a newer version: https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks/files/4776995
