### ISSUE TITLE
Mouse Tweaks cannot be used on the Ae2 terminal interface

### ISSUE THREAD

**Issue by starsky648** [YaLTeR/MouseTweaks#124]
In the AE2 terminal interface of version 1.20.1fabric, I shifted + left clicked on items several times, and nothing went directly into my backpack, so I had to drag it into my backpack manually.Other places can be used normally

**Comment by YaLTeR** [comment]
AE2 probably uses a completely custom GUI for its interface. Not much Mouse Tweaks can really do here unfortunately.
