### ISSUE TITLE
Compatibility issue with Nether Chested by Fuzs

### ISSUE THREAD

**Issue by LessThanBenji** [YaLTeR/MouseTweaks#127]
This issue is two-fold:

Firstly, the RMB tweak causes an instant crash if used in the Nether Chest inventory. Most likely an issue to be fixed on its end, and it's on its issue tracker already, but thought I'd mention it here too; and

Secondly, the scroll wheel tweak doesn't recognize the Nether Chest's increased stack size of 512 -- it stops adding items to stacks inside the Chest via scrolling once the stack reaches 64 items. It doesn't cause a crash, it just stops pulling more items.

(I've noticed these issues in 1.20.1, using Fabric 0.15.6, with Mouse Tweaks v2.25 and Nether Chested v8.0.3).

**Comment by YaLTeR** [comment]
> Firstly, the RMB tweak causes an instant crash if used in the Nether Chest inventory. Most likely an issue to be fixed on its end, and it's on its issue tracker already, but thought I'd mention it here too; and

Yeah, crashes are likely not Mouse Tweaks fault.

> Secondly, the scroll wheel tweak doesn't recognize the Nether Chest's increased stack size of 512 -- it stops adding items to stacks inside the Chest via scrolling once the stack reaches 64 items. It doesn't cause a crash, it just stops pulling more items.

That sounds weird. In Mouse Tweaks I use `getMaxStackSize()` everywhere, I don't hardcode anything.

**Comment by YaLTeR** [comment]
Thanks, I will take a look.

**Comment by YaLTeR** [comment]
I fixed the scrolling issue in 91ece88; I don't get any crashes.

**Comment by YaLTeR** [comment]
https://modrinth.com/mod/mouse-tweaks/version/1.20-2.26-fabric

https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks/files/5230279
