### ISSUE TITLE
1.20.6 Crashes on launch

### ISSUE THREAD

**Issue by awesomeman5** [YaLTeR/MouseTweaks#132]
When booting with mouse tweaks the game crashes immediately. https://pastebin.com/tSnrGKXq

**Comment by YaLTeR** [comment]
That's weird, it works here using the vanilla launcher. Could you try that?

**Comment by YaLTeR** [comment]
Oh wait, I think I uploaded the wrong file on Modrinth by accident :facepalm:

**Comment by YaLTeR** [comment]
Okay, I reuploaded the files, please try again.

**Comment by awesomeman5** [comment]
works now! ya silly goose
