### ISSUE TITLE
Add artifacts for game version 1.20.5

### ISSUE THREAD

**Issue by MaxLevs** [YaLTeR/MouseTweaks#134]
Some game launchers cannot install mod on 1.20.5

**Comment by YaLTeR** [comment]
1.20.5 lasted a few days and was superseded by a 1.20.6 bugfix release. Please just use 1.20.6.

**Comment by MaxLevs** [comment]
What's the difficulties to add intermediate version support?
There are some mods that don't have support for 1.20.6 for some reason but 1.20.5. And you have support for 1.20.4 and 1.20.6 but 1.20.5 is missed. It's strange.

**Comment by YaLTeR** [comment]
All mods will support 1.20.6 soon. I just don't understand why I should spend the time on a version which lasted a few days.

**Comment by MaxLevs** [comment]
What time? I don't realy understand. Does 1.20.5 contains some breaking changes? What needs to be done to release the artifact? Fix code? Or chagne metadata? Or just rebuild? Don't you have pipelines configured?

**Comment by YaLTeR** [comment]
I need to put in the correct version numbers for all components, build multiple versions of the mod, then install multiple mod loaders, then manually test the mod every single mod loader. It's quite a bit of effort, not a click one button and forget.

**Comment by MaxLevs** [comment]
Okay. You have a point. 10q for explanation
