### ISSUE TITLE
Crashing when used with Axiom

### ISSUE THREAD

**Issue by omakthe1st** [YaLTeR/MouseTweaks#137]
Using this mod on Fabric 1.20.6 with Axiom installed causes a crash when clicking. I have no other mods installed (except Fabric API), and all mods (and Fabric) are on the latest update, and both mods work when used separately

[Here's the crash report](https://github.com/user-attachments/files/15753956/crash-2024-06-09_22.24.50-client.txt)

Versions just in case:
Fabric 0.15.11
Fabric API 0.100.0
Mouse Tweaks 2.26
Axiom 3.0.0

**Comment by YaLTeR** [comment]
Uhh, could you report this to Axiom too? Not sure who's at fault here, and what exactly the problem is.

**Comment by omakthe1st** [comment]
will do!

**Comment by omakthe1st** [comment]
I was told to wait for Fabric API 0.100.0 support, or use 0.99.0..

**Comment by omakthe1st** [comment]
just tried again with not enough crashes installed and it said something about fabric screen api if thats of any use, it also doesnt happen in 1.21 so if you didnt change much that could mean its on axioms side

**Comment by YaLTeR** [comment]
I didn't really change anything for the 1.21 update

**Comment by omakthe1st** [comment]
then its probably from their side, cause axiom 3.1 fixed it on 1.21 and it still hasnt released for 1.20.6 where the problem is happening.

**Comment by omakthe1st** [comment]
nvm 3.1 released for 1.20.6 just not on modrinth. anyways sorry to bother thank you for your time
