### ISSUE TITLE
Fabric 1.21 Memory Dump lag

### ISSUE THREAD

**Issue by Bloodpoison** [YaLTeR/MouseTweaks#139]
Ive no idea what the issue is, but deleteing Mouse tweaks was the only way to fix Mini lags happening everytime my Memory dumps, ive tried everything else before it, Memory increase decrease doesnt matter, maybe you got a mem leak or something? idk

**Comment by YaLTeR** [comment]
Huh, what do you mean by memory dumps?

**Comment by Bloodpoison** [comment]
I Apologize after more testing it appears that the error still Popped up, apperently it takes a while after starting before it appears i forgot i postet here

So this Mod wasnt the issue im so sorry, soz

But by memory dumps i meant whenever Memory resets before loading up again, you know how it dumps all 5secs, it also means i still got the error q-q and i cant find the fix for it
