### ISSUE TITLE
Not in config file

### ISSUE THREAD

**Issue by sh0rtlin3r** [YaLTeR/MouseTweaks#141]
I installed the newest version into the mods folder, but i cant configure the mod, because it doesnt appear in the config file. How can i fix this?

**Comment by YaLTeR** [comment]
`.minecraft/config/MouseTweaks.cfg`

**Comment by sh0rtlin3r** [comment]
Its not there

**Comment by YaLTeR** [comment]
Did you launch the game and open a world?

**Comment by sh0rtlin3r** [comment]
Yes

**Comment by YaLTeR** [comment]
Not sure then, works here
