### ISSUE TITLE
Scroll config setting doesn't change behavior

### ISSUE THREAD

**Issue by alexgibbs606** [YaLTeR/MouseTweaks#142]
All The Forge 10.11 - Mouse Tweaks 2.25.1 - Minecraft 1.20.1

I'm used to scroll down to push (I think of it has scroll down to reduce stack size). With the current modlist I'm using on the current version, updating the configuration value in the file or in the menu doesn't have an effect on the behavior of the scrolling direction.

Debug mode didn't log anything that seemed useful, but I'm happy to debug and identify the issue with more information.

**Comment by YaLTeR** [comment]
Are you sure it's the Mouse Tweaks item scrolling that is being used? There are some other mods that do it.

**Comment by alexgibbs606** [comment]
This is a great point. After disabling MouseTweaks from the menu, I was still able to scroll items. I'll continue looking for the culprit, but it's not MouseTweaks!

**Comment by alexgibbs606** [comment]
For those who might find this useful, the "Simple Inventory Sorter" mod, version 23.0.1 includes a scroll wheel move option, and can be disabled in the config for that mod.
