### ISSUE TITLE
Opening config crashes on 1.21

### ISSUE THREAD

**Issue by Meryl** [YaLTeR/MouseTweaks#146]
Using version 2.26 on NeoForge, opening the config through the button in the mods-menu results in the following crash: 
[crash-2024-08-02_16.18.23-client.txt](https://github.com/user-attachments/files/16471569/crash-2024-08-02_16.18.23-client.txt)

**Comment by YaLTeR** [comment]
Uh, weird. Maybe something changed in the API and needs an update on Mouse Tweaks side

**Comment by YaLTeR** [comment]
Fixed in a23701efa6f38c7a84633b2b22a6b1f6988489cb.
