### ISSUE TITLE
Mouse Tweaks 2.26 fabric Lunarclient

### ISSUE THREAD

**Issue by papalooi44** [YaLTeR/MouseTweaks#149]
everytime i start the game and have mousetweaks active it crash
[eb0c163d-968f-401a-8f46-4aadf830445d-master.log](https://github.com/user-attachments/files/16845369/eb0c163d-968f-401a-8f46-4aadf830445d-master.log)

**Comment by YaLTeR** [comment]
I cannot do anything about this since Lunar has its own obfuscation. This is also a duplicate of https://github.com/YaLTeR/MouseTweaks/issues/135.
