### ISSUE TITLE
Wheel tweak takes priority over scrolling through bundles

### ISSUE THREAD

**Issue by BlueStaggo** [YaLTeR/MouseTweaks#152]
Scrolling up in a bundle works just fine, but when I scroll down with a container open, instead of scrolling through items in the bundle, it move items from the bundle into the container. I'm not sure if this is intentional but it feels quite annoying. I'm on Fabric 1.21.3.

**Comment by YaLTeR** [comment]
Indeed. It is not intentional. I'll need to see how Minecraft handles bundles and how to fix this.

**Comment by cgsdev0** [comment]
i think a simple solution might just be to special case bundles, so that they aren't able to be moved with the mouse wheel

you could potentially still allow moving empty bundles

**Comment by YaLTeR** [comment]
I special cased bundles in e3e66e848900a662997743afd9d8d698cfd4e4ea which fixes this issue. Unfortunately, the built-in Fabric API hook doesn't tell the mod Minecraft's scroll handling return value, so this is not a generic solution.

**Comment by YaLTeR** [comment]
Should be the exact same fix for 1.20
