### ISSUE TITLE
[1.12.2] Wheel tweak does nothing

### ISSUE THREAD

**Issue by kasufert** [YaLTeR/MouseTweaks#153]
Mod version: 2.10.1
MC version: 1.12.2
Loader: Cleanroom 0.2.3-alpha
Modpack: Supersymmetry 0.1.34
Java version: OpenJDK 21.0.4.0.7-1 Windows x86_64 (Red Hat Build)
OS: Windows 11 Pro 23H2 22635.4367

Disabled and enabled mod, disabled and enabled wheel tweak in config. Tried with quark and vanilla chests.

Expected behavior: Open chest, hover mouse over item stack, and scroll up or down to insert/take items from inventory.

Actual behavior: Scrolling does nothing.

**Comment by YaLTeR** [comment]
Could you try with just Mouse Tweaks and no other mods?

**Comment by kasufert** [comment]
I stopped using Cleanroom because it kept breaking other mod functionality. I'm using forge now and everything is working. :)

**Comment by YaLTeR** [comment]
Alright, nice
