### ISSUE TITLE
Got crashes with immersive enginering

### ISSUE THREAD

**Issue by cjser** [YaLTeR/MouseTweaks#16]

**Comment by cjser** [comment]
Got crashes when I try to open the box from immersive engineering since last update of that mod.
[crash-2018-12-10_19.13.11-client.txt](https://github.com/YaLTeR/MouseTweaks/files/2668313/crash-2018-12-10_19.13.11-client.txt)

**Comment by YaLTeR** [comment]
Thanks for the report, can you tell me if you can reproduce the crash consistently; if yes, then how to reproduce it? What versions of the mods involved are you using?

**Comment by cjser** [comment]
Mouse tweak 2.9 and immersive eng 1.12 87. Happens every time I try to open toolbox from imm eng since his last update

**Comment by YaLTeR** [comment]
Have you reported it to immersive engineering? If it's their update that introduced the crash maybe it's something on their side. I'll definitely take a look at the Mouse Tweaks side later though.

**Comment by cjser** [comment]
Yes, it appears I am not the only one. Not reference to mouse tweaks in the other reports

**Comment by YaLTeR** [comment]
I'm gonna guess this was an immersive engineering crash, please reopen if you can reproduce it on the latest versions of the mods involved.
