### ISSUE TITLE
Shift click issue with JEI and Quark

### ISSUE THREAD

**Issue by mezz** [YaLTeR/MouseTweaks#19]
Steps to reproduce the bug:
 * Create a Minecraft instance with Forge, MouseTweaks, JEI, and Quark (and AutoRegLib, a Quark dependency).
 * Start a creative-mode world.
 * Open a crafting table and fill your inventory with items cheated from JEI.
    * ![2019-01-11_23 17 34](https://user-images.githubusercontent.com/916092/51070518-737a2180-15f7-11e9-8d7f-e1ce63d47491.png)
 * Open a crafting recipe that can be shift-clicked into the crafting table, the [+] button must be above an item in your inventory if the recipe gui was not open.
    * ![2019-01-11_23 17 39](https://user-images.githubusercontent.com/916092/51070521-7f65e380-15f7-11e9-9e63-ba03443eea37.png)
 * Shift click the [+] button and observe extra items are moved into the crafting grid.
    * ![2019-01-11_23 17 44](https://user-images.githubusercontent.com/916092/51070525-842a9780-15f7-11e9-9079-ae2a0c204843.png)

Quark moves items into the crafting grid with its "Better Craft Shifting" feature, but there is no conflict between just JEI and Quark. 
Mouse Tweaks must be present to cause the issue seen here, if it's not there then the shift-click puts the recipe into the crafting table without any extra items.

I do not know why this is happening, so I am hoping to try to figure it out with you and @vazkii

**Comment by YaLTeR** [comment]
There's a similar issue with MT wheel interacting _through_ JEI's GUI as if it didn't exist (#2), I haven't looked into that yet but I suspect it's the same issue.

**Comment by mezz** [comment]
I will take a look and submit a PR soon.

**Comment by mezz** [comment]
Submitted a PR here: https://github.com/YaLTeR/MouseTweaks/pull/20
