### ISSUE TITLE
Default config didn't generate

### ISSUE THREAD

**Issue by CREEATION** [YaLTeR/MouseTweaks#21]
I started up Minecraft and my already existing world multiple times, wondering where the config is.
However, upon changing & saving settings via "Mod Options..." in the main menu, it was created.

**Comment by YaLTeR** [comment]
Good point, I need to make it create the config if it does not exist as soon as the mod is loaded.

**Comment by YaLTeR** [comment]
Fixed in https://github.com/YaLTeR/MouseTweaks/commit/d05223bd64635e2a1deb09c4e85e91e0ce29a67c
