### ISSUE TITLE
1.14?

### ISSUE THREAD

**Issue by HFinner** [YaLTeR/MouseTweaks#25]
Hello, just wondering if you will be working on the mod to release for 1.14/.2. Thanks!

**Comment by VoidsShadow** [comment]
This isn't what GitHub Issues are for...
If you found a bug or have a suggestion, then feel free to open an Issue on GitHub.

**Comment by YaLTeR** [comment]
I was working on updating it to the new Forge in [this branch](https://github.com/YaLTeR/MouseTweaks/tree/minecraft-1.13) however the work temporarily halted. I will continue it after I sort out the exams this month.

**Comment by YaLTeR** [comment]
Hey, I have just finished the first beta update to 1.14.4. Download it [here](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks/files/2793893) and please report any issues you come across.
