### ISSUE TITLE
[1.14.4] Crash with 28.1.22 please update.

### ISSUE THREAD

**Issue by ProsperCraft** [YaLTeR/MouseTweaks#26]
[1.14.4] Mouse Tweaks 2.11

When your mod is added to my pack is causes this crash-
https://github.com/McJtyMods/RFToolsPower/issues/26

Pack-
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by YaLTeR** [comment]
Which log from that issue should I be looking at? Also are you sure it's Mouse Tweaks causing the crash (so removing Mouse Tweaks alone makes it not crash)?

**Comment by ProsperCraft** [comment]
The latest.log there and the crash right above it.

Yes removing mouse tweaks stops the crash.

I think you will find updating to .22 will stop the issue.

1.14 has been problematic with crashes with forge because it never shows you the stacktrace for the actual mod causing the issue when they are not updated, so you have to get a stable base and add a mod and if it casues some other mod to crash you know that is the one with the problem(the one you added).  Try with my latest release of my pack and add your mod and load it.

**Comment by YaLTeR** [comment]
Does this work? Rename to `.jar`, I had to rename to `.zip` so GitHub would let me upload. [MouseTweaks-2.11-mc1.14.4.zip](https://github.com/YaLTeR/MouseTweaks/files/3663236/MouseTweaks-2.11-mc1.14.4.zip)

**Comment by ProsperCraft** [comment]
nope still sidedness- 
https://gist.github.com/ProsperCraft/4f0203b075055b61ada8c8e861149080

Sidedness changed in 1.14 not sure if you knew that.

**Comment by ProsperCraft** [comment]
Crash report-
https://paste.fedoraproject.org/paste/Rr83ksBqiXc6ev6no80MYQ/

Logs-
[debug.log](https://github.com/YaLTeR/MouseTweaks/files/3663416/debug.log)
[latest.log](https://github.com/YaLTeR/MouseTweaks/files/3663417/latest.log)

**Comment by YaLTeR** [comment]
Oh, huh. Well, MT isn't supposed to be used on the server.

**Comment by ProsperCraft** [comment]
If you set up sidedness, this will be your last sidedness bug report :)..

I am testing with a client now.

**Comment by ProsperCraft** [comment]
yes, this version load in the client and doesn't crash.

**Comment by ProsperCraft** [comment]
Please upload to curse so I can include it in my pack? :)

**Comment by YaLTeR** [comment]
Yeah, I'll try to do that tomorrow, kinda busy this weekend.

**Comment by YaLTeR** [comment]
Could you try loading this one on the server? It should hopefully disable itself and not crash. [MouseTweaks-2.11-mc1.14.4.zip](https://github.com/YaLTeR/MouseTweaks/files/3672907/MouseTweaks-2.11-mc1.14.4.zip)

**Comment by ProsperCraft** [comment]
Sorry, had to rebuild the whole pack.  I will add this next update thank you.
