### ISSUE TITLE
[1.14.4] Weird shift click behavior with secretrooms

### ISSUE THREAD

**Issue by GabrielAndreescu** [YaLTeR/MouseTweaks#27]
Problem: shift clicking multiple items on the same type don't combine them into one stack, instead 2 or more stacks are created, when you click one of them, it combines them as if it was a visual glitch

How to recreate: new sp world, get some wood, split it into your inv, then shift click DRAG over the splited items so they go into your hotbar

Versions:
mc_1.14.4
MouseTweaks-2.12
forge_28.1.0 & 28.1.39 (tested on both versions to make sure)

**Comment by GabrielAndreescu** [comment]
This was caused by a datapack... my bad, I forgot to remove the datapacks folder

**Comment by YaLTeR** [comment]
So it happened even when shift-clicking regularly, without MT? In theory shift click-drag should behave the exact same way as regular shift-clicking.

**Comment by GabrielAndreescu** [comment]
I'm still trying to debug this thing...it's so annoying, sometimes it happens sometimes it doesn't I'm not sure what's causing it, I've removed the world folder on my server to get rid of datapacks, and it's still happening, on a local single player world it doesn't with the same mods, so I assumed it's the data packs...I'm going crazy

**Comment by YaLTeR** [comment]
Could you test with and without Mouse Tweaks on your setup, and with just Mouse Tweaks on a clean Minecraft?

**Comment by GabrielAndreescu** [comment]
Update:
without MT on my setup it doesn't happen
with MT on clean install it doesn't happen

I guess enable one mod at a time with MT and see what's causing this?

**Comment by YaLTeR** [comment]
I suppose, yeah. You could also try binary searching for the mod.

**Comment by GabrielAndreescu** [comment]
Binary searching? Can you explain please?

**Comment by YaLTeR** [comment]
Remove half of the mods. If the problem persists, it's in the installed half of the mods. If the problem goes away, it's in the half that you removed. Repeat the process until you find the culprit.

This way it'll take you about log_2(mod count) steps, rather than potentially (mod count).

**Comment by GabrielAndreescu** [comment]
Oh thanks, I didn't know how you call it, but that's what I did so I got down to 2 mods:
MouseTweaks-2.12-mc1.14.4.jar
secretrooms-6.0.1.jar

**Comment by YaLTeR** [comment]
Could you report it to secretrooms and link this issue please?

**Comment by GabrielAndreescu** [comment]
![2019-10-13 18-52](https://user-images.githubusercontent.com/3175443/66718275-b2d5d880-edea-11e9-98f6-5bdc29a3c7b6.gif)

**Comment by Wyn-Price** [comment]
I was unable to reproduce it with the latest forge, secret rooms and mouse tweaks. (Also, reminds me that the manifest is currently broken for secretrooms).
![javaw_WW9XdMsRpi](https://user-images.githubusercontent.com/15876682/66718452-05f45f00-eddc-11e9-833d-ec9ac1831861.png)
![w2KQOhebj6](https://user-images.githubusercontent.com/15876682/66718455-07258c00-eddc-11e9-94f1-8cfc7d7deff5.gif)

**Comment by GabrielAndreescu** [comment]
I can reproduce it with clean install...
I'm under linux by the way, maybe that has something to do with it?

**Comment by GabrielAndreescu** [comment]
@Wyn-Price the world you tested in, was it a creative type world or survival?

I kept testing, if I create a world of type creative (doesn't matter if I change it to survival afterwards) I cannot reproduce, but if I start with a survival type world, and literally punch the trees or open to lan with cheats (which I used to test until now), then it happens.

Can anyone else test please? I need to know if it's on my end only.

**Comment by Wyn-Price** [comment]
I tested with it in creative mode, then changed to survival mode. Having it not work based on the game type the world starts with makes 0 sense to me.  Definitively not caused by secretrooms

**Comment by GabrielAndreescu** [comment]
It doesn't make sense for me either, can you please check by starting on a survival world?

**Comment by Wyn-Price** [comment]
Okay so i having it in surival mode, I was able to reproduce the issue. Loading everything up in a developer enviroment, I was able to figure out what the issue is. When you shift drag, it looks like the item stack is moved on both the client and the server. 

The issue arises from some overlooked code in the custom tooltip that the switch probe uses. In the tooltip event. I do `ItemStack#getOrCreateChildTag`, which means clientside, the stack has the tag compund, but serverside it does not. Hence why the stack doesn't get put in the right place. 

No idea why this only happenes in single player generated worlds, that part makes 0 sense.

**Comment by GabrielAndreescu** [comment]
I actually found out too, I commented all your events one by one (I'm new to modding) ... but yeah, maybe next time try to be a little more open with ppl that try to help you out, no offense.

**Comment by Wyn-Price** [comment]
I'm perfectly open with people trying to help me out, but over the years you accumilate so many bug reports that miss out crutial information or just aren't to do with your mod whatsoever that i physically just don't have time to investigate all of them myself. 

From first glance, this just didn't look like anything secretrooms could cause. Clearly I was wrong. 
Related commit: https://github.com/Wyn-Price/SecretRooms/commit/b90902bda0621704685a8ec2ed99072a63d860a0

**Comment by YaLTeR** [comment]
Thanks for figuring this out! I'm glad the root cause was found and fixed.
