### ISSUE TITLE
[1.14.4] Crash

### ISSUE THREAD

**Issue by LCTMarti** [YaLTeR/MouseTweaks#29]
if you fill up the Workbench like this: 
64 64 64
64 64 64
64 64  A
where A is any number of item except 64 and then trying to fill in a stack by shift right clicking it causes a crash instead of filling up the last slot

**Comment by YaLTeR** [comment]
Uhh, I don't think Mouse Tweaks does anything on shift-right click? Are you sure it's not some other mod?

**Comment by LCTMarti** [comment]
Yeah, shift left click, my bad

**Comment by YaLTeR** [comment]
Do you mean shift-left click drag or just shift-left click?

Either way Mouse Tweaks shouldn't be doing anything weird here. Please post the crash log.

**Comment by tgstyle** [comment]
Could this be the issue, just happens to be dragging when doing these options? Here is the crash.
https://gist.github.com/tgstyle/8475bf9e860a54068db7926cc3f33e9c

**Comment by YaLTeR** [comment]
Can you reproduce this every time? Which container? Could you record a video? Could you try with just Mouse Tweaks and no other mods?

**Comment by tgstyle** [comment]
Yes it happens in any container when left click dragging. I think it may be related to FastWorkbench, I am testing it now.

**Comment by tgstyle** [comment]
It's not FastWorkbench, I tried a fresh install with just Mouse Tweaks on Forge. Holding left click while doing it once seems fine to empty slots, but then picking up a stack and left click dragging over existing items while staying in the same GUI crashes. I tried with just a MC chest.

**Comment by tgstyle** [comment]
Also shift-left click dragging from inventory to a chest slot that is not yet full crashes.

**Comment by YaLTeR** [comment]
So clean 1.14.4 with just Forge and Mouse Tweaks, and you can reproduce it? Could you record a short video showcasing the issue?

**Comment by tgstyle** [comment]
Correct, 1.14.4 with just forge and Mouse Tweaks.
https://www.dropbox.com/s/t9dg7qn5jrdfb8a/Minecraft%201.14.4%202020-03-31%2022-02-28.mp4?dl=1

**Comment by YaLTeR** [comment]
Thanks, I will look into this.

**Comment by YaLTeR** [comment]
I can't reproduce this crash. Here's a video of me doing the same movements as you: https://streamable.com/6hfnsu

**Comment by tgstyle** [comment]
Were you holding the LMB the whole time?

**Comment by tgstyle** [comment]
Bizarre thing is, I can't get it to reproduce today either. It could be done very easily. I will keep testing and let you know the results.

**Comment by YaLTeR** [comment]
> Were you holding the LMB the whole time?

I tried to decipher from the video when you were releasing the LMB and release it at the same moments.

**Comment by tgstyle** [comment]
Right at the very end of the video dragging right and then left while holding the LMB is when it crashed. I still cannot get it to reproduce yet.

**Comment by YaLTeR** [comment]
In the end of the video I let go of LMB to put down the chest stack, then hold it again on the empty slot and drag onto the rightmost chest slot.

**Comment by tgstyle** [comment]
That should have triggered it. I don't know what would have changed in the last few days, unless there was a library update.

**Comment by YaLTeR** [comment]
Well, please reopen if you can reproduce this on the most recent version like 1.18.
