### ISSUE TITLE
BitBucket: Crash to desktop opening refined storage

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/MouseTweaks#3]
Old issue link: https://bitbucket.org/YaLTeR/mouse-tweaks/issues/19/crash-to-desktop-opening-refined-storage

**Comment by Mochnant** [comment]
I've had the same crash happen.  Anything I can do to assist debugging?

**Comment by YaLTeR** [comment]
Not yet, sorry, I haven't looked into this yet.

**Comment by Morpheus1101** [comment]
Just had this crash occur myself with RS

**Comment by falkreon** [comment]
Might actually be related to #2 - for me, I have a four-mod crash between RS, ExtraUtils2, MouseTweaks, and JEI, where, while in refined storage, and when I have all ingredients present for the recipe, I click plus to pull in the recipe for the Biome Marker, it hard-crashes Minecraft without fail. No other recipe seems to have this problem.

**Comment by YaLTeR** [comment]
I think this was fixed in the other mods? If this still happens on the latest versions please reopen.
