### ISSUE TITLE
Conflicts with tinkers construct

### ISSUE THREAD

**Issue by SamuraiShogun1102** [YaLTeR/MouseTweaks#30]
Whenever I use a crafting grid from tinkers construct or any forge table from tinker's construct clones items and sticks them onto slots.

**Comment by YaLTeR** [comment]
Hello, did you try removing just Mouse Tweaks to see if it's causing the issue? Could you describe exactly what you're doing to cause the issue?

**Comment by SamuraiShogun1102** [comment]
I was trying to combine a diamond on my tinkers pickaxe on a tool forge and then it started to clone whenever I move my mouse onto a slot and when I placed the pickaxe on the center, it also cloned on other slots in the tool forge. I’m sorry I couldn’t describe it correctly.

**Comment by YaLTeR** [comment]
What makes you think it was Mouse Tweaks?

**Comment by SamuraiShogun1102** [comment]
When I removed mouse tweaks the tinker tables worked normally.

**Comment by YaLTeR** [comment]
Did you do any right mouse hold-and-dragging or left mouse hold-and-dragging to hit the bug?

**Comment by SamuraiShogun1102** [comment]
Yeah

**Comment by YaLTeR** [comment]
What exactly did you do?

**Comment by SamuraiShogun1102** [comment]
I’m sorry I couldn’t remember how to describe it.

**Comment by YaLTeR** [comment]
I can't diagnose the issue unless you tell me the exact steps you did, which include some Mouse Tweaks-related functionality like RMB dragging. You could record a video if that's easier.

**Comment by SamuraiShogun1102** [comment]
I was about to to use a tool forge to combine a tinkers pickaxe with a diamond, when I put the pickaxe in the middle by left-clicking it on the middle slot, then when I was about to drag a diamond onto a slot around the center slot, it cloned whenever I drag onto a slot and I couldn’t remove all of them, when I finished combining the pickaxe with I diamond, I have trouble removing it from the slot.

**Comment by YaLTeR** [comment]
Did you hold your right mouse button while dragging the diamond?

**Comment by SamuraiShogun1102** [comment]
Just a few minutes, I'm having trouble uploading the video

**Comment by SamuraiShogun1102** [comment]
I was wrong, I got that issue months ago and I didn't publish it.
and sorry I couln't find a way to upload the video.
