### ISSUE TITLE
Crash with Anvil (1.14.4) (Possibly #15)

### ISSUE THREAD

**Issue by BrisingrAerowing** [YaLTeR/MouseTweaks#31]
[Crash Log](https://gist.github.com/BrisingrAerowing/d58becd99e2740b37ff3d919deca0c21)

From #15, I think this may be a bug in Vanilla, but I think you should know anyways.

Related: McJtyMods/TheOneProbe#351

**Comment by YaLTeR** [comment]
Interesting

**Comment by YaLTeR** [comment]
The linked issue says someone got it without Mouse Tweaks, so I'm assuming it's not a Mouse Tweaks issue.
