### ISSUE TITLE
Scrolling in JEI results in item transfer

### ISSUE THREAD

**Issue by TherminatorX** [YaLTeR/MouseTweaks#35]
MC 1.12.2
Mod version 2.10

Scrolling through JEI options while in a large chest inventory and such pulls items to/from the player inventory.

Basically #2 but in more recent versions.

**Comment by YaLTeR** [comment]
Try toggling the mouse handling setting?

**Comment by TherminatorX** [comment]
Toggling to non-smooth scrolling handling appears to remove this issue.

**Comment by YaLTeR** [comment]
Yeah, that's the compromise to have to take in pre-1.13 unfortunately; I've left the default on smooth-but-with-this-issue.

**Comment by TherminatorX** [comment]
Odd choice to have the default option to be buggy behavior in my opinion, due to not seeing any significant performance improvement with the non-smooth scrolling.

**Comment by YaLTeR** [comment]
To me it's very visible, and it occurs every time you scroll rather than under specific circumstances (scrolling over a JEI GUI on top). Thus, I made this trade-off.
