### ISSUE TITLE
Mouse Tweaks causing client crash

### ISSUE THREAD

**Issue by SirOMGitsYOU** [YaLTeR/MouseTweaks#36]
[crash-2020-09-20_02.33.34-client.txt](https://github.com/YaLTeR/MouseTweaks/files/5251404/crash-2020-09-20_02.33.34-client.txt)

**Comment by YaLTeR** [comment]
Which inventory? Have you tried without Mouse Tweaks?

**Comment by SirOMGitsYOU** [comment]
> Which inventory? Have you tried without Mouse Tweaks?

Player inventory I believe - and no crash without mouse tweaks

**Comment by YaLTeR** [comment]
Can you consistently reproduce it? What exactly do you do? Can you reproduce with just Mouse Tweaks installed and no other mods?

**Comment by SirOMGitsYOU** [comment]
> Can you consistently reproduce it? What exactly do you do? Can you reproduce with just Mouse Tweaks installed and no other mods?

It wasn't my crash Its a modpack I have one of the users had this crash consistently twice - I'll get the information of what he was doing.

**Comment by ZZWolf47** [comment]
[crash-2020-10-04_20.35.04-client.txt](https://github.com/YaLTeR/MouseTweaks/files/5330080/crash-2020-10-04_20.35.04-client.txt)

**Comment by YaLTeR** [comment]
@ZZWolf47 thanks for the log. Can you consistently reproduce it? What exactly do you do? Can you reproduce with just Mouse Tweaks installed and no other mods?

**Comment by ZZWolf47** [comment]
[crash-2020-10-07_23.44.07-client.txt](https://github.com/YaLTeR/MouseTweaks/files/5345196/crash-2020-10-07_23.44.07-client.txt)
for me it just happened again. it just happens when i go to pick something up something on random. This time it happened when i went to pick up my digital miner

**Comment by YaLTeR** [comment]
Can you reproduce with just Mouse Tweaks installed and no other mods?

**Comment by ZZWolf47** [comment]
Not with this modpack. At the moment it is only happening when i go to pickup something with the atomic dissembler.

**Comment by YaLTeR** [comment]
Then there's a high chance it's not a Mouse Tweaks issue.

**Comment by ZZWolf47** [comment]
At this time I am on ABOE. It my not be... however since it is listing Mouse Tweaks on the crash screen I figured I share it with you to help you out.

**Comment by YaLTeR** [comment]
Yeah, unfortunately it's next to impossible to tell what's happening from this crash log. Since Mouse Tweaks is fairly simple and the crash doesn't occur without other mods, it's likely the cause is in another mod. That's happened a number of times before.
