### ISSUE TITLE
[1.16.3] Mouse Tweaks crash when scrolling items with quark oddities backpack

### ISSUE THREAD

**Issue by hibikutek** [YaLTeR/MouseTweaks#37]
Forge version 34.1.25
Crash Log [here](https://pastebin.com/dR4qBxRx)

Steps to reproduce:
Equip backpack from Quark Oddities.  Use scroll wheel to place item into backpack.

**Comment by YaLTeR** [comment]
Thanks for the log! I suspect this is an issue in Quark or in fastbench. Could you please report there too?

**Comment by jacket430** [comment]
Hey there! One of the players on my server recently came across the same issue. I will report it to Quark and FastWorkbench too. Appears to be an issue between this mod and Quark. 

[Log file here](https://hastebin.com/jofobuciqo.rb)

**Comment by YaLTeR** [comment]
Thanks for reporting to their tracker! So was it fixed? Can I close this issue?
