### ISSUE TITLE
Cannot right-click items into shulker

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/MouseTweaks#38]
From CurseForge comments:

> on 1.16.3, after installing this I can no longer right click to drop items into a shulker box in my inventory

Need to look into this.

**Comment by SwanX1** [comment]
The bug seems to be related to Quark and it's features such as "Right-click drop items into shulker" and the seed pouch. Disabling `RMBTweak` seems to fix it, however disabling this feature is a crutch for me personally, could be great if this could get resolved

**Comment by Kevadroz** [comment]
Also afects bundles plus, possibly a problem with AutoRegLib

**Comment by YaLTeR** [comment]
Closing in favor of https://github.com/YaLTeR/MouseTweaks/issues/51.
