### ISSUE TITLE
Crash when right clicking inventory crafting window

### ISSUE THREAD

**Issue by Cryotheus** [YaLTeR/MouseTweaks#43]
Got a crash report for you. I right clicked a stack of bones into my invetory crafting grid for this to transpire. I was connected to a multiplayer server when this happened.
[crash-2021-01-23_21.49.23-client.txt](https://github.com/YaLTeR/MouseTweaks/files/5861492/crash-2021-01-23_21.49.23-client.txt)

**Comment by YaLTeR** [comment]
> ```
> Caused by: java.lang.ClassCastException: net.minecraft.inventory.CraftingInventory cannot be cast to > shadows.fastbench.gui.CraftingInventoryExt
> 	at shadows.fastbench.asm.PlayerContainerHooks.onCraftMatrixChanged(PlayerContainerHooks.java:16) ~[fastbench:4.4.1] {re:classloading}
> 	at net.minecraft.inventory.container.PlayerContainer.func_75130_a(PlayerContainer.java) ~[?:?]
> ```

Seems like a fastbench issue, could you report there as well?
