### ISSUE TITLE
Mark mod as client side only (also in 1.16)

### ISSUE THREAD

**Issue by Flockel** [YaLTeR/MouseTweaks#45]
Bug #34 is marked as fixed but my installation of MouseTweaks still triggers the red X on the server. When I look at your repository the fix for #34 is only pulled in the master branch but still missing in branch 1.16.

Seeing master only 2 commits ahead of 1.16 it should be easily merged, right?

**Comment by YaLTeR** [comment]
The branches are for older Minecraft versions when the code is no longer compatible, so the latest 1.16.2+ version is currently on master. The problem is that I just haven't made a release yet. Is this issue annoying enough to warrant a new release or can it wait until the next Minecraft version?

**Comment by Flockel** [comment]
With "next Minecraft version" you mean 1.17? I'm building a custom modpack for a 1.16 server which is starting soon, so waiting would not be an option. I'll probably leave MouseTweaks out then.

**Comment by YaLTeR** [comment]
It's not much of a bother, let me push a new release then.

**Comment by Flockel** [comment]
Thanks, appreciated!

**Comment by YaLTeR** [comment]
https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks/files/3202662 should be approved in a few mins.

**Comment by Flockel** [comment]
Works flawlessly! Thanks again!
