### ISSUE TITLE
[1.7.10] Scrolling bug

### ISSUE THREAD

**Issue by FadingFog** [YaLTeR/MouseTweaks#49]
При попытке переместить предмет откуда/куда либо с помощью колёсика мыши, происходит баг и больше 1 предмета не получается переместить.
P.S. На 1.16 всё отлично работает (как и на 1.12 если не ошибаюсь)

https://user-images.githubusercontent.com/10418075/114038007-28a8ec00-988a-11eb-8039-562c28b9841a.mp4

**Comment by YaLTeR** [comment]
Это Not Enough Items, у которого та же функциональность. Нужно поставить WheelTweak = 0 в конфиге Mouse Tweaks, чтобы отключить.
