### ISSUE TITLE
[1.16.5] Quark's feature "right-click to add" broken when MouseTweaks installed.

### ISSUE THREAD

**Issue by Gbergz** [YaLTeR/MouseTweaks#51]
Title^

The Quark feature "right-click to add" to Shulker Boxes & the Seed pouch gets broken when MouseTweaks installed.

You can "**solve**" this by disabling the line in the **MouseTweaks** config "**RMBTweak**=" from 1 to 0.

However if its fixable without disabling that config option that would be lovely.

**MouseTweaks Version:** 2.14-mc1.16.2
**Quark Version:** r2.4-311

RMBTweak Enabled:
https://streamable.com/lmfor8

RMBTweak config Disabled:
https://streamable.com/tvsj9s

**-** Gbergz

**Comment by YaLTeR** [comment]
I decided to disable RMBTweak by default until a different solution, which doesn't cancel click events, is implemented in Mouse Tweaks.

**Comment by YaLTeR** [comment]
Should be fixed in 1cb1143e1b99a7d1554e9177b584c969bbc0fe1c for vanilla bundles and any mod items that behave similarly.

**Comment by DatenThielt** [comment]
So by fixed,   Do you mean that setting RMBTweak to 0 should resolve this, or that disabling this should no longer  be needed to work with the Quark Right click into a shulker?  I only ask as I still have to set RMBTweak to 0 in order to get the functionality to work (Using version 2.14) .  If that is intended, please ignore :)

**Comment by YaLTeR** [comment]
Disabling this should no longer be needed to work with the Quark Right click into a shulker. Note however that the first version with the fix is Mouse Tweaks 2.19.

**Comment by DatenThielt** [comment]
Ahh got ya,  Thank you for the response.  So because 1.16.x is 2.14  I'm guessing it wont be backported.  Thanks again!
