### ISSUE TITLE
Crashing when using shift-drag to put stuff in sophisticated backpack

### ISSUE THREAD

**Issue by Talyda** [YaLTeR/MouseTweaks#52]
Getting a crash when I use the shift-drag (or shift-click) feature of mouse tweaks to put stuff in leather sophisticated backpack. 

**To Reproduce**
Press "B" to open backpack and inventory
shift-drag mouse along inventory to get it all to just pop into backpack
Crash

**Expected behavior**
No crashy

**Versions**
Using 
sophisticatedbackpacks-1.16.4-2.4.0.259.jar 
MouseTweaks-2.14-mc1.16.2.jar  
forge 36.1.4

Crash log here:
https://gist.github.com/Talyda/a361b9880bcdc130731b8f8775c4da10

Latest.log here:
https://gist.github.com/Talyda/53f19aa822c08b01ce4a593741f9720f

Am also going to copy paste this to sophisticated backpack issues and put link to it here:
https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/143

*edits* it's not happening with every item - I was able to put random things - string, wheat, paper, a lead, a slime sapling from tinkers - but then it crashed on a saddle, and iron armour
Tested again with the saddle, and normal picking it up and dragging the saddle to the backpack was fine - shift clicking it into there was fine

**Comment by YaLTeR** [comment]
Gonna guess this is a SophisticatedBackpacks issue, thanks for posting it there too.

**Comment by Talyda** [comment]
I wasn't sure, so figured both places to be sure!

**Comment by YaLTeR** [comment]
Closing because looks like another SophisticatedBackpacks crash.
