### ISSUE TITLE
Scroll wheel tweak skipping scroll "clicks"

### ISSUE THREAD

**Issue by BLucky-gh** [YaLTeR/MouseTweaks#54]
Usually with mouse tweaks I was able to just take a single item per scroll wheel "click", but now if I just do a single "click", it doesn't work, I have to scroll 2-3 notches on my wheel at once (one by one doesn't work) to grab a single item, and sometimes it grabs two (which makes me think there might be scroll wheel acceleration shenanigans involved, if that's even a thing?)

there's no template for submitting a bug report here so I'll just give all the info I have:
Minecraft version: 1.12.2
Mod version: 2.10-mc1.12.2
Modpack: FTB university
it's on MacOS if that could impact anything, which it really shouldn't because JVM and stuff
also the mouse is logitech g903 if that helps.

**Comment by YaLTeR** [comment]
That's strange. Could you send the Mouse Tweaks config file? Also is this the same with vanilla Minecraft containers too?

**Comment by BLucky-gh** [comment]
Here's the mousetweaks.cfg file:
```
RMBTweak=1
LMBTweakWithItem=1
LMBTweakWithoutItem=1
WheelTweak=1
WheelSearchOrder=1
WheelScrollDirection=1
OnTickMethodOrder=Forge, LiteLoader
ScrollHandling=0
Debug=0
```

And yes I first noticed this behavior with vanilla chests. Also scrolling to cycle items in toolbar works fine and it moves one item per "click" so java/minecraft *are* actually detecting individual steps on the mouse wheel

**Comment by YaLTeR** [comment]
Could you try with only Mouse Tweaks installed and no other mods? Also could you try `ScrollHandling=1` in the config?

**Comment by BLucky-gh** [comment]
Tried on a bare minecraft forge installation with just mouse tweaks, both with scrollhandling 0 and 1, and I restarted minecraft between config changes just in case, and the issue still persists. (I was gonna mention that ftb university has a smooth scrolling mod too but I just now proved that's not the issue so idk)

**Comment by YaLTeR** [comment]
Ah, I remember something like that from another macOS user. They even added a setting specifically for their mouse.

Please try this updated Mouse Tweaks, set `ScrollItemScaling=1` in the config: https://bxt.rs/files/MouseTweaks-2.10.1-mc1.12.2.jar

**Comment by BLucky-gh** [comment]
The updated version works perfectly with `ScrollItemScaling=1`, thanks a lot.

**Comment by BLucky-gh** [comment]
Also for anyone reading this issue in the future, I believe YaLtEr was referring to #22

**Comment by YaLTeR** [comment]
Thanks for testing, I uploaded this version to CurseForge.
