### ISSUE TITLE
Loom and Stonecutter wheel tweak compatibility

### ISSUE THREAD

**Issue by PegasDoggeAM** [YaLTeR/MouseTweaks#56]
Minecraft 1.14 introduced Loom and Stonecutter, but wheel tweak isn't working with it.
Kinda showcase of the issue [here](https://www.youtube.com/watch?v=R_LZOWfCX74).

**Comment by YaLTeR** [comment]
They don't work because those inventories have slots with a scrollbar, which takes all wheel input for itself, just like in the creative menu. I'm not sure if this is something I want to override because it's the behavior people will expect coming from vanilla.

**Comment by PegasDoggeAM** [comment]
Then I'll probably close this issue, considering it exhausted.
