### ISSUE TITLE
Bundles not working with mod installed

### ISSUE THREAD

**Issue by Philraz4** [YaLTeR/MouseTweaks#58]
Bundles not working with mod installed
Version MouseTweaks-2.14-mc1.17.1

**Comment by YaLTeR** [comment]
I guess it's a conflict with RMB tweak or something?

**Comment by YaLTeR** [comment]
Potential lead by @Corail31:

> If you look the bundle item, you'll see there're 2 new methods in the item class (overrideStackedOnOther & overrideOtherStackedOnMe).
>
> They handle right click to "combine" or "put into bundle". Your mod probably doesn't handle them yet but soon :)

**Comment by Philraz4** [comment]
the work around in #51 seens to solve it
