### ISSUE TITLE
[Bug]1.16.5 Cross-compatibility mod bug. When using (integrated crafting)autocrafting and removing a single item by scrolling it out(mousetweaks), the crafter starts a new crafting recipe

### ISSUE THREAD

**Issue by MisterObvious25** [YaLTeR/MouseTweaks#59]
This is a Cross-compatibility mod bug. I already posted it on the Integrated Crafting Github here https://github.com/CyclopsMC/IntegratedCrafting/issues/74. Mod author states that this problem likely needs to be fixed in MouseTweaks.

See for full description of the problem and mod authors respons > https://github.com/CyclopsMC/IntegratedCrafting/issues/74

**Mod versions**
Versions:

Common Capabilities
kroeser
CommonCapabilities-1.16.5-2.8.0.jar

Cyclops Core
kroeser
CyclopsCore-1.16.5-1.12.0.jar

Integrated Crafting
kroeser
IntegratedCrafting-1.16.5-1.0.19.jar

Integrated Dynamics
kroeser
IntegratedDynamics-1.16.5-1.10.3.jar

Integrated Terminals
kroeser
IntegratedTerminals-1.16.5-1.2.8.jar

Integrated Tunnels
kroeser
IntegratedTunnels-1.16.5-1.8.7.jar

Mouse Tweaks
YaLTeR
MouseTweaks-2.14-mc1.16.2.jar

**Comment by YaLTeR** [comment]
This was fixed in IC.
