### ISSUE TITLE
[Info]  1.18-pre5 Fabric

### ISSUE THREAD

**Issue by Stelk** [YaLTeR/MouseTweaks#60]
I have a working build for fabric 1.18-pre5 that a contributor may find useful.  Unfortunately it will bork the non-fabric builds so I am not creating a PR just yet.  Based on the structure of the code I could not find a simple way to support running in a dev environment and from a jar using intermediate names.  Rewriting of the framework detection (mcp/fabric/forge/vanilla) may be required.  Or just create a seperate branch for each.  

You can find the code here: https://github.com/Stelk/MouseTweaks/tree/minecraft-fabric-1.18-pre
artifact:  https://github.com/Stelk/MouseTweaks/releases/download/fabric/MouseTweaks-fabric-mc1.18-pre5-2.16.jar

**Comment by YaLTeR** [comment]
Hello! Interesting, thanks for the link!

I deliberately used official mappings instead of yarn since they work with both Forge (since 1.17) and Fabric letting me support both with one code-base easily. I think it makes the most sense to stick to the official mappings for this reason.

**Comment by Stelk** [comment]
Cool, I'll revert to the official mappings and see how that changes things.. I'm new to MC modding and was blindly following the Yarn remapping instructions.  https://fabricmc.net/wiki/tutorial:migratemappings

**Comment by YaLTeR** [comment]
I updated to 1.18 here: 695d3977c22c7e98e1d8cffa75a16762517c8ecc
