### ISSUE TITLE
Does not function in 1.18 with Replay Mod

### ISSUE THREAD

**Issue by Chedski** [YaLTeR/MouseTweaks#61]
If Replay Mod is installed, the features Mouse Tweaks adds just don't work. There's no errors anywhere as far as I can tell, but nothing happens when I try to use a Mouse Tweaks feature (eg. shift click drag). Stopping the recording doesn't fix it either.

**Comment by YaLTeR** [comment]
Thanks for the report! I made an issue on Replay Mod asking which of us should fix this and how.

**Comment by YaLTeR** [comment]
Could you please try this new build and write if the bug is fixed for you? https://github.com/YaLTeR/MouseTweaks/suites/4635222628/artifacts/125567042
