### ISSUE TITLE
MC 1.18.1/MouseTweaks-Fabric-2.17 doesn't work with Architectury

### ISSUE THREAD

**Issue by DraLUSAD** [YaLTeR/MouseTweaks#62]
After updating Minecraft to 1.18.1, the MouseTweaks stops working, holding down commonly used buttons to quick move items no longer works, does the mod have any conflics with other mods, such as "InventorySorter-Fabric"?

**Comment by YaLTeR** [comment]
Hm, it works here with just Mouse Tweaks installed. What exactly are you pressing and trying to do?

**Comment by DraLUSAD** [comment]
I'm holding Shift on an empty space, then mouse dragging over all the items, but nothing happens, even holding on to an item then dragging over the same items doesn't soak the items to cursor

**Comment by YaLTeR** [comment]
Does it work with just Mouse Tweaks installed? If you could find which other mod causes the issue it would be greatly helpful.

**Comment by DraLUSAD** [comment]
Alrighty, I've just got MT(+FabricAPI) And I can safely say, it works fine, now the more pain staking question is to which mods stops this function

**Comment by DraLUSAD** [comment]
[latest.log](https://github.com/YaLTeR/MouseTweaks/files/7710734/latest.log)
Not sure if this helps, but I couldn't see any forms of errors to why MT stops working, however, it was working fine in 1.18, with these mods, now it doesn't, this is going to take a while

**Comment by YaLTeR** [comment]
If you just replace MT with the 2.16 version does it still not work?

**Comment by DraLUSAD** [comment]
even 2.16, stops working, could be a recent mod I added, I'll check that out in a bit

**Comment by ImAK9** [comment]
> even 2.16, stops working, could be a recent mod I added, I'll check that out in a bit

If you end up finding the mod causing it please let me know as I'm having the same issue.

**Comment by ImAK9** [comment]
I'd take a huge guess on it being forgeconfigapiport but I cant test right now.

**Comment by DraLUSAD** [comment]
I found the offending mod "architectury-3.2.49"
But there has been an update since, going to test this now

**Comment by DraLUSAD** [comment]
Even the update stops this function >_<, At least I found the source

**Comment by YaLTeR** [comment]
Thanks very much! I'll look into it.

**Comment by DraLUSAD** [comment]
going to do one more test and pull it out + its required mods

**Comment by DraLUSAD** [comment]
Took out that API+dependencies, and MT works fine, so yes, Architectury is the issue here

**Comment by ImAK9** [comment]
> If you just replace MT with the 2.16 version does it still not work?

Seems to be working with as intended with 2.16, updating to 2.17 breaks it.

**Comment by YaLTeR** [comment]
Looks like Architectury is doing something weird...

**Comment by DraLUSAD** [comment]
ahh nice, glad I could help pin point another mods issue xD

**Comment by YaLTeR** [comment]
Could you please test this new build? https://github.com/YaLTeR/MouseTweaks/suites/4669145856/artifacts/127002187

**Comment by DraLUSAD** [comment]
Looking good, thank you for the fix 👍

**Comment by YaLTeR** [comment]
Thanks for testing!
