### ISSUE TITLE
[1.18.1] Crashes Dedidicated Server

### ISSUE THREAD

**Issue by RoyalReject** [YaLTeR/MouseTweaks#63]
MouseTweaks-forge-mc1.18-2.20.jar crashes dedicated server its trying to access a client side only class
https://pastebin.com/hQKRxNQL
This problem does not exist in MouseTweaks-forge-mc1.18-2.19.jar

**Comment by YaLTeR** [comment]
Oops, I'll fix this.

Note however that Mouse Tweaks is clientside-only and is not needed on the server.

**Comment by YaLTeR** [comment]
Uploaded 2.21 which won't crash.
