### ISSUE TITLE
1.18.1 Dedicated Server Crash

### ISSUE THREAD

**Issue by Potatomonium** [YaLTeR/MouseTweaks#64]
On updating to MouseTweaks 2.20, it crashes my server on launch

https://pastebin.com/Y8pbyd8U

**Comment by YaLTeR** [comment]
Oops, I'll fix this.

Note however that Mouse Tweaks is clientside-only and is not needed on the server.

**Comment by YaLTeR** [comment]
Uploaded 2.21 which won't crash.
