### ISSUE TITLE
please upload version 2.22 to modrinth

### ISSUE THREAD

**Issue by yesn0t** [YaLTeR/MouseTweaks#66]
currently the newest MouseTweaks on modrinth is v2.16 (which i've unknowingly been using all this while o_o ) compared to v2.22 on curseforge

Thanks x)

**Comment by YaLTeR** [comment]
Oh, you use modrinth? Sorry, I was kinda lazy to update it, I'll do it now.

**Comment by yesn0t** [comment]
thank you !
