### ISSUE TITLE
[1.12.2] Crash with latest RFTools Version

### ISSUE THREAD

**Issue by MasterEnderman** [YaLTeR/MouseTweaks#7]
Forge: 14.23.4.2705
McJtyLib: 3.0.0
RFTools: 7.50
MouseTweaks: 2.8
Crash Report: https://paste.dimdev.org/raw/olozenehex

The game crashes as soon as you open an Storage Scanner from RFTools. There have been some changes to McJtyLib recently, which likely are the reason for the crash.

**Comment by McJty** [comment]
Hmm in my GUI class I override isMouseOverSlot() (which I made public with an AT) to detect if my mouse is over a slot and then do something. Seems it is messing up there somehow

**Comment by McJty** [comment]
I'm not exactly sure what is going on but it looks as if you're calling a GuiContainer function before something in my GUI class has had a chance to initialize. But I can fix that on my side by initializing it then. That will fix the null pointer exception and should be fine.

**Comment by MasterEnderman** [comment]
Fixed with the next update of McJtyLib.
https://github.com/McJtyMods/McJtyLib/issues/74
