### ISSUE TITLE
Unknown options for the settings. There is no documentation to be found anywhere.

### ISSUE THREAD

**Issue by Guy-Yudovich** [YaLTeR/MouseTweaks#70]
I am currently playing Enigmatica 6 Expert - E6E on minecraft version1.16.5 and forge version 36.2.29
One of the mods is Mouse Tweaks and it's configs are not what I am used to. When I press the Mods button on the main menu and go to Mouse Tweaks the Config button is disabled so I opened the configs file but it's all numbers, how can I know what number means what on each setting? I can't find a documentation of the options for the settings.

**Comment by Guy-Yudovich** [comment]
Only the default settings are documented there

**Comment by YaLTeR** [comment]
That's because most of them are on/off, so 1 means on and 0 means off.

**Comment by YaLTeR** [comment]
- 0 = normal
- 1 = inverted
- 2 = inventory position aware
- 3 = inventory position aware inverted

**Comment by Guy-Yudovich** [comment]
Thanks a lot
