### ISSUE TITLE
Question[1.7.10]

### ISSUE THREAD

**Issue by Petrol12** [YaLTeR/MouseTweaks#71]
Hello, I would like to know why the mod does not need to be installed on the server? I'm not good at programming.

I play with friends on the server, the mod cannot be replaced by quickly dragging things into chests, etc.

On version 1.12.2, the mod works on the server, what's wrong with version 1.7.10?

**Comment by YaLTeR** [comment]
The mod is clientside-only. You don't need it installed on the server, it will work even when installed only on the client. It doesn't do anything and never did anything when installed on the server.
