### ISSUE TITLE
When loading minecraft with multiMC on Linux, mouse tweaks says it needs fabric, when fabric is already installed.

### ISSUE THREAD

**Issue by u12bdragon** [YaLTeR/MouseTweaks#72]
I created a 1.18.2 instance, installed fabric through the "version" tab of MultiMC, then added mouse tweaks to the mod list. When I launch the game, I get the error:
Mod 'Mouse Tweaks' (mousetweaks) 2.22 requires any version of fabric, which is missing!
I have several performance mods installed as well, such as Sodium, which run completely fine

I tried installing fabric API, even though it is not listed as a dependency, and this actually lets the game run, but it freezes up "Minecraft is not responding." I tried waiting it out to no avail.

MultiMC version: 0.6.15-3244 on lin64
Fabric version: tested with 0.13.3, 0.14.0, and 0.14.4, but I suspect the issue happens with any version.
Mousetweaks version: 2.22
OS: Ubuntu 20.04.4 LTS

**Comment by YaLTeR** [comment]
Not sure, last time I tested with vanilla launcher it worked fine with both Fabric and Forge.

**Comment by YaLTeR** [comment]
I'll close this because I suspect this is not a Mouse Tweaks issue. Feel free to reopen if you find that it is certainly a Mouse Tweaks issue and not a MultiMC issue.
