### ISSUE TITLE
[1.18.2 Forge] Would you happen to know which mod in my list is messing up this mods scroll functionality?

### ISSUE THREAD

**Issue by TheUnderTaker11** [YaLTeR/MouseTweaks#73]
To start off, this issue does NOT happen with just MouseTweaks installed. It's some interaction with another mod causing the failure.
![image](https://user-images.githubusercontent.com/16872377/168687801-ab8265a1-b06e-46f0-b175-9ac99ef853c0.png)
![image](https://user-images.githubusercontent.com/16872377/168687858-9ffcdf70-b984-4dbd-94ed-52c14b36b7c8.png)
![image](https://user-images.githubusercontent.com/16872377/168687894-420075b0-a6e2-4aa8-8538-2594351de58a.png)
![image](https://user-images.githubusercontent.com/16872377/168687927-c6d64d84-0fb6-491f-a510-68e38ee7a9e2.png)

Sorry to ask it here, but I figured maybe you might already know some mods that are incompatible? The scroll functionality in this pack is completely borked.

**Comment by TheUnderTaker11** [comment]
Another note, it doesn't happen in singleplayer, but does happen on a server, super weird. Long shot asking here but figured it couldn't hurt

**Comment by YaLTeR** [comment]
Uhh, idk, nothing that rings a bell immediately here. You could try disabling Mouse Tweaks scrolling in the config menu and see if that helps.

**Comment by TheUnderTaker11** [comment]
To clarify, I'm unsure if it's a mod conflict at all, as it only happens when connected to a server. Have you tested this mod using a local server?

**Comment by YaLTeR** [comment]
I haven't but it should work fine. You could try removing some mods to see if the issue disappears, or trying with just Mouse Tweaks alone.

**Comment by TheUnderTaker11** [comment]
After a ton of testing, the issue was Alex's mobs mod adding empty NBT data to every item. (There was/is already a new version of the mod that fixed this issue, we just didn't have it.)

**Comment by YaLTeR** [comment]
Ah, alright, good to know.
