### ISSUE TITLE
Mouse tweaks does not show up in my mods list.

### ISSUE THREAD

**Issue by lxly9** [YaLTeR/MouseTweaks#74]
I installed the latest version of mouse tweaks from modrinth for 1.18.2, the weird thing is now, that it doesnt show up or work at all, not in any configs, etc. Im really confused rn T-T

**Comment by YaLTeR** [comment]
Did you install the right version? There's Forge and there's Fabric versions, they are separate.

**Comment by lxly9** [comment]
yes i downloaded the fabric, forge, quilt version from the version tab (the second one from the top)

**Comment by YaLTeR** [comment]
I am... not sure how to interpret this. Here are the two versions:

![image](https://user-images.githubusercontent.com/1794388/170742834-c9f7eeec-cfc9-4d61-bcc7-3db7e352f2b7.png)

The top one is fabric and won't work for forge, and the bottom one is forge and won't work for fabric.

**Comment by lxly9** [comment]
![Screenshot (129)](https://user-images.githubusercontent.com/102386118/170743165-974f6bf9-c546-4ec7-9546-9c61fc78c902.png)

**Comment by lxly9** [comment]
sorz, forgot to add the text, i downloaded the second one (it does not have quilt sorry about that)

**Comment by YaLTeR** [comment]
It has two files. By default it downloads the forge version as you can see in the filename. If you use fabric you need the fabric version.

**Comment by lxly9** [comment]
Ah oh my god, yeah my bad, im so sorry ;-;
