### ISSUE TITLE
[Question] Disable scrolling tweaks only

### ISSUE THREAD

**Issue by NFLD99** [YaLTeR/MouseTweaks#75]
as per title, how can i disable only the scrolling tweaks and keep everything else as its very frustrating when using AE2

**Comment by ShibeTemple** [comment]
what solution did you find

**Comment by YaLTeR** [comment]
Try WheelTweak=0 in config?

**Comment by ShibeTemple** [comment]
is there not a way to blacklist certain UI containers?

**Comment by YaLTeR** [comment]
Unfortunately there isn't
