### ISSUE TITLE
Port to 1.19

### ISSUE THREAD

**Issue by gohkenytp** [YaLTeR/MouseTweaks#76]
I'm just letting you guys know that 1.19 is released, so anyone can port it with great pleasure.

**Comment by YaLTeR** [comment]
Thanks for letting me know! Sorry for the delay, had very busy few days.

**Comment by YaLTeR** [comment]
I've updated the mod to 1.19, it's now up [on CurseForge](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks/files).
