### ISSUE TITLE
[1.19] Error when loading Forge Version 41.0.64

### ISSUE THREAD

**Issue by Two-FourXR** [YaLTeR/MouseTweaks#78]
Wanted to add MT as a client-side QoL mod, though when I installed it with a couple other mods four of them (Xaero's MM & WM, Creativecore, and MT) failed with the error "java.lang.reflect.InvocationTargetException: null"

Not sure what I did wrong or if I did anything wrong at all. Help would be greatly appreciated.

**Comment by Two-FourXR** [comment]
Sorry for those, new to GitHub

**Comment by YaLTeR** [comment]
Please post the full crash log.

**Comment by Two-FourXR** [comment]
Will do

**Comment by Two-FourXR** [comment]
[crash-2022-07-07_20.54.05-fml.txt](https://github.com/YaLTeR/MouseTweaks/files/9068117/crash-2022-07-07_20.54.05-fml.txt)

**Comment by YaLTeR** [comment]
Looks kinda weird, does Mouse Tweaks work on its own if you remove other mods? If so then it's likely some other mod causing the incompatibility

**Comment by Two-FourXR** [comment]
No, the error persists.

**Comment by YaLTeR** [comment]
So just clean Minecraft 1.19 Forge with just Mouse Tweaks? Could you post the crash log for that?

**Comment by Two-FourXR** [comment]
Apologies for the delay.
[crash-2022-07-08_09.34.29-fml.txt](https://github.com/YaLTeR/MouseTweaks/files/9072430/crash-2022-07-08_09.34.29-fml.txt)

**Comment by YaLTeR** [comment]
Thanks, I'll need to look into it.

> Apologies for the delay.

It's ok to not respond instantly, GitHub is not a real-time chat.

**Comment by SeptJack** [comment]
im getting the same error with just mouse tweaks installed aswell

**Comment by Two-FourXR** [comment]
It might be the Forge version itself. Due to how new it is some mods may be too old for 41.0.64. I ran with five other mods, and four of the six failed (Xaero's MM and WM, CC, and MT). JEI and Ambient Sounds didn't crash. I had a theory before that the Forge version was causing the crashes, but then I thought about JEI and AS not crashing along with the other four.

Kinda just throwing my thoughts out there, not sure what the true problem is haha. Not tech savvy enough yet.

**Comment by SeptJack** [comment]
yh ive done some testing and its forge itself its not just mousetweaks as already been said and the same errors from 41.0.64 al the way upto 41.0.87, the only fix ive found so far is downgrading forge to 41.0.63

**Comment by YaLTeR** [comment]
Thanks for pinpointing the Forge version!

**Comment by YaLTeR** [comment]
Fixed in https://github.com/YaLTeR/MouseTweaks/commit/2c10082a584194d8ab7731a7d8b3963cead46c34, https://github.com/YaLTeR/MouseTweaks/commit/2fe9b08dc00878a40bb75becb092afaeb2cbae75. Please download Mouse Tweaks 2.23 on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks/files) or [modrinth](https://modrinth.com/mod/mouse-tweaks/versions).
