### ISSUE TITLE
[1.19] Mod failed to load correctly

### ISSUE THREAD

**Issue by HPLS2002** [YaLTeR/MouseTweaks#80]
Mouse Tweaks (mousetweaks) has failed to load correctly
_java.lang.reflect.InvocationTargetException: null_

Log:
[latest.log](https://github.com/YaLTeR/MouseTweaks/files/9170474/latest.log)

**Comment by HPLS2002** [comment]
[crash-2022-07-22_16.15.09-fml.txt](https://github.com/YaLTeR/MouseTweaks/files/9170494/crash-2022-07-22_16.15.09-fml.txt)

Also this

**Comment by YaLTeR** [comment]
You are using Forge 41.0.63. Either update Forge, or use Mouse Tweaks 2.22.

> If you use Forge 41.0.93 or lower, you need Mouse Tweaks 2.22, the previous version.
