### ISSUE TITLE
Fabric Version for 1.19 missing

### ISSUE THREAD

**Issue by Darkwolf202** [YaLTeR/MouseTweaks#88]
I presume this version in the 'Files' tab is supposed to be for 1.19?

![image](https://user-images.githubusercontent.com/57463653/183838295-64f7643f-6807-4324-b89e-6e01d9bbfaa8.png)

I suspected it was just a typo, but when I try to launch the game it says mod is only compatible with 1.16.2

![image](https://user-images.githubusercontent.com/57463653/183838374-58000d76-4b0e-411d-a850-46f0cf020c3c.png)

**Comment by YaLTeR** [comment]
https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks/files/3828448

1.19+ means "1.19 and subsequent 1.19 versions"
