### ISSUE TITLE
Opening GUI results in brief freeze when both Forge and Liteloader are installed 

### ISSUE THREAD

**Issue by hjoyn** [YaLTeR/MouseTweaks#9]
Minecraft Ver. 1.10.2
Mouse Tweaks Ver. 2.8

Opening any gui (pause menu, chat, inventory, crafting table, chest, furnace, modded elements such as psi radial wheel) results in a brief freeze before the gui opens. Requires both Forge and Liteloader to be installed, although it still occurs if the mod is disabled in the liteloader menu.

**Comment by YaLTeR** [comment]
Hmm does it occur if you remove the mod from the mods folder? Also does it happen every time or just the first time for every given GUI?

**Comment by hjoyn** [comment]
What do you mean by remove it from the mods folder? And it occurs every time you open a GUI, including subsequent times.

**Comment by YaLTeR** [comment]
I mean that you should try removing Mouse Tweaks from the mods folder to check if it really is Mouse Tweaks causing it.

**Comment by hjoyn** [comment]
Yes, I narrowed it down to MouseTweaks. This occurs with only MouseTweaks installed.

**Comment by YaLTeR** [comment]
So this occurs even with Forge + LiteLoader + MouseTweaks without any other mods? What Forge and LL versions are you using?

**Comment by hjoyn** [comment]
Yes. 
Forge: 12.18.3.2185
LiteLoader: 1.10.2 Release

**Comment by YaLTeR** [comment]
I'll try to reproduce it tomorrow.

**Comment by YaLTeR** [comment]
I installed clean Minecraft 1.10.2 + Forge 12.18.3.2185 + LiteLoader 1.10.2 + Mouse Tweaks 2.8, created a new creative world, put a chest and a crafting bench down and I don't get any freezes when opening either of those, or the chat menu.

**Comment by YaLTeR** [comment]
Can you reproduce it following the same steps?
