### ISSUE TITLE
Won't load in 1.19

### ISSUE THREAD

**Issue by ChillBrian** [YaLTeR/MouseTweaks#91]
I installed the mod on fabric and the mod won't load on 1.19.2
[2022-09-03-1.log.gz](https://github.com/YaLTeR/MouseTweaks/files/9482787/2022-09-03-1.log.gz)

**Comment by YaLTeR** [comment]
I don't see mouse tweaks here. Did you download the Fabric version of the mod?

**Comment by ChillBrian** [comment]
I'm an idiot, sorry
