### ISSUE TITLE
Bug/server lag

### ISSUE THREAD

**Issue by Kasia1403** [YaLTeR/MouseTweaks#92]
[Client thread/INFO] [STDOUT]: [yalter.mousetweaks.Logger:DebugLog:11]: [Mouse Tweaks] No valid handler found; MT is disabled.

This message lags my world in Minecraft 1.12.2. Could this be fixed ?

**Comment by YaLTeR** [comment]
Messages shouldn't lag the game. Can you try removing Mouse Tweaks and seeing if the lag disappears?

**Comment by Kasia1403** [comment]
But could You explain me what does it mean "No valid handler found." ? Maybe it is a bug ?

**Comment by Kasia1403** [comment]
Eh, maybe it is also something with Biomes You Go mod ? I added the mod with fixes for it. Maybe it will help.

**Comment by YaLTeR** [comment]
It's not a bug, it means that you've opened a custom GUI that mouse tweaks doesn't support.
