### ISSUE TITLE
Scroll direction seems to not change

### ISSUE THREAD

**Issue by CinnamonShaey** [YaLTeR/MouseTweaks#94]
i am on 1.19 and im trying to change the scroll direction but i have tried both setting it to 1 and 0 and both scroll the same way so it does not seem to work

**Comment by CinnamonShaey** [comment]
damn, yeah works fine in an isolated environment, would you mind helping me on finding the mod that messes with it on the modpack or is that beyond the scope of what you can do

**Comment by CinnamonShaey** [comment]
actually not needed! found the mod that was causing it it was "simple inventory sorter" it had kebinds for mousewheel up and mousewheel down, to do exactly the same as your mod, tho i like your mods execution better as i can change the direction 👌

**Comment by YaLTeR** [comment]
You'll need to do it yourself I'm afraid. The usual suspects are simple inventory sorter, mouse wheelie, etc.

**Comment by YaLTeR** [comment]
Ah, yeah, cool, that's what I thought

**Comment by CinnamonShaey** [comment]
sorry for wasting your time! i should have checked something so simple as that!
