### ISSUE TITLE
No RMB and LMB Tweaks

### ISSUE THREAD

**Issue by notIkibo** [YaLTeR/MouseTweaks#95]
Fabric 0.14.11/0.68 API
1.19.2
Mouse Tweaks: 2.22

I can't use RMB (your stuff you drag over your crafting table to craft stuff) and LMB (to either take or deploy your stuff from/on a chest). They were both on and nothing happens (you just take one and the "holding LMB and Shift" doesn't do anything. Sad times

**Comment by notIkibo** [comment]
Scrolling works just fine, but I really really prefer LMB Tweaks

**Comment by YaLTeR** [comment]
Could you try with just Mouse Tweaks and no other mods installed? Might be some other mod conflicting.

**Comment by YaLTeR** [comment]
Feel free to reopen with more details.
