### ISSUE TITLE
Minecraft 1.19.3 crash when opening settings menu

### ISSUE THREAD

**Issue by YukiAyase** [YaLTeR/MouseTweaks#96]
_I've not tested every feature of MouseTweaks yet_ **but** it doesn't crash the game and works as intended nor do anything crazy at all until you open MouseTweaks settings
I'm sure this crash is related to the changes Mojang did
<br/>
**This was tested in a testing environment with only a few select mods**
<br/>
Steps to reproduce:
1.) Boot up Minecraft 1.19.3 with latest version of MouseTweaks
2.) Go to Mod Menu and locate MouseTweaks
3.) Select MouseTweaks and attempt opening the settings menu, game crashes
<br/>
Mods when tested

fabric-api-0.69.1 1.19.3
Fastload 1.19.3-2.6.6
ferritecore-5.1.0-fabric
lazydfu-0.1.3
memoryleakfix-1.19.3-0.7.0
modmenu-5.0.2
MouseTweaks-fabric-mc1.19-2.22
sodium-fabric-mc1.19.3-0.4.6rev.7ec4e0f-dirty
viafabric-0.4.9 22-main

Log: https://mclo.gs/pZq3ed0

_If this has already been reported before, please close the issue!_

**Comment by YaLTeR** [comment]
Indeed. Thanks for the detailed report.

**Comment by YaLTeR** [comment]
Fixed in Mouse Tweaks 2.24, uploaded to CurseForge & modrinth.
