### ISSUE TITLE
[1.19.2 - Fabric 0.14.14] Suddenly stopped working.

### ISSUE THREAD

**Issue by Nimrod108** [YaLTeR/MouseTweaks#99]
Are there any known incompatibilities in this modlist?

[Better Compatibility Checker (by Gaz_)](https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker)
[You're in Grave Danger (by b1n_ry)](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)
[ARRP (by one_point_o)](https://www.curseforge.com/minecraft/mc-mods/arrp)
[YUNG's Extras (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras-fabric)
[Pick Up Notifier [Forge & Fabric] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/pick-up-notifier)
[VanillaTweaks [Fabric & Forge] (by StrikerRocker)](https://www.curseforge.com/minecraft/mc-mods/vanillatweaks)
[Kambrik (by Ejektaflex)](https://www.curseforge.com/minecraft/mc-mods/kambrik)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Client Tweaks (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/client-tweaks-fabric)
[Duckling (by Frogipher)](https://www.curseforge.com/minecraft/mc-mods/duckling)
[Geophilic – Biome Overhauls (by bebebea_loste)](https://www.curseforge.com/minecraft/mc-mods/geophilic)
[Easy Shulker Boxes (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/easy-shulker-boxes)
[No Resource Pack Warnings (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/no-resource-pack-warnings)
[EnhancedVisuals (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/enhancedvisuals)
[Dynamic FPS (by juliand665)](https://www.curseforge.com/minecraft/mc-mods/dynamic-fps)
[Better Than Mending (by legobmw99)](https://www.curseforge.com/minecraft/mc-mods/better-than-mending)
[Dawn API (by Hugman_76)](https://www.curseforge.com/minecraft/mc-mods/dawn)
[Puzzles Lib [Forge & Fabric] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Wandering Collector (by Siphalor)](https://www.curseforge.com/minecraft/mc-mods/wandering-collector)
[Explorer's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/explorers-compass)
[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[Another Furniture (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/another-furniture)
[Replanter (by Areuthreateningme)](https://www.curseforge.com/minecraft/mc-mods/replanter)
[Effortless Fabric (by huskcasaca)](https://www.curseforge.com/minecraft/mc-mods/effortless-fabric)
[Critters and Companions (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/critters-and-companions)
[More Banner Features (by KxmischesDomi)](https://www.curseforge.com/minecraft/mc-mods/more-banner-features)
[Cardinal Components (by UpcraftLP)](https://www.curseforge.com/minecraft/mc-mods/cardinal-components)
[Visual Workbench (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
[YUNG's Bridges (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-bridges-fabric)
[Better Third Person (by Socolio)](https://www.curseforge.com/minecraft/mc-mods/better-third-person)
[Immersive Paintings [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings)
[Galosphere (by orcinus73)](https://www.curseforge.com/minecraft/mc-mods/galosphere)
[Indium (by comp500)](https://www.curseforge.com/minecraft/mc-mods/indium)
[YetAnotherConfigLib (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/yacl)
[YUNG's Better Strongholds (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds-fabric)
[Inventory HUD+ (by dmitrylovin)](https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge)
[YUNG's API (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric)
[Immersive Armors [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-armors)
[Zoomify (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/zoomify)
[Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
[Entity Culling Fabric/Forge (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[Magnum Torch (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/magnum-torch-forge)
[BetterNether (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betternether)
[YUNG's Better Dungeons (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons-fabric)
[Goblin Traders (Fabric) (by jab125twitchy)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders-fabric)
[ThonkUtil (by jab125twitchy)](https://www.curseforge.com/minecraft/mc-mods/thonkutil)
[Aquatic Torches (by realmayus)](https://www.curseforge.com/minecraft/mc-mods/aquatic-torches)
[Create Fabric (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
[YUNG's Better Desert Temples (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples-fabric)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Marium's Soulslike Weaponry (by mariumbacchus)](https://www.curseforge.com/minecraft/mc-mods/mariums-soulslike-weaponry)
[Oh The Biomes You'll Go Refabricated (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric)
[🔨 Frame API (by andantet)](https://www.curseforge.com/minecraft/mc-mods/frame-api)
[Sodium Extra (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/sodium-extra)
[Elytra Slot (Fabric) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/elytra-slot-fabric)
[AdventureZ (by Globox_Z)](https://www.curseforge.com/minecraft/mc-mods/adventurez)
[Macaw's Lights and Lamps (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Universal Ores (Fabric) (by Hugman_76)](https://www.curseforge.com/minecraft/mc-mods/universal-ores-fabric)
[Wolves Of Other Furs (W.O.O.F) (by itsmineblock11)](https://www.curseforge.com/minecraft/mc-mods/woof)
[Reacharound (by spAnser)](https://www.curseforge.com/minecraft/mc-mods/reacharound)
[Iris Shaders (by coderbot)](https://www.curseforge.com/minecraft/mc-mods/irisshaders)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Better Fps - Render Distance[Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance-fabric)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Falling Leaves (Fabric) (by RandomMcSomethin)](https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric)
[Timber bumped (by ADDB0)](https://www.curseforge.com/minecraft/mc-mods/timber-1-19-2)
[Go Fish (by Draylar1)](https://www.curseforge.com/minecraft/mc-mods/go-fish)
[xali's Enchanted Books (by xalixilax)](https://www.curseforge.com/minecraft/texture-packs/xalis-enchanted-books)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Easy Magic [Forge & Fabric] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
[Windchimes (by hibiscvs)](https://www.curseforge.com/minecraft/mc-mods/windchimes)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Trading Post [Forge & Fabric] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/trading-post)
[Alternate Current (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
[Connectible Chains [Fabric] (by legoatoom)](https://www.curseforge.com/minecraft/mc-mods/connectible-chains)
[Leaves Be Gone (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/leaves-be-gone)
[Bountiful (Fabric) (by Ejektaflex)](https://www.curseforge.com/minecraft/mc-mods/bountiful-fabric)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Better Statistics Screen (Fabric/Forge) (by TheCSDev)](https://www.curseforge.com/minecraft/mc-mods/better-stats)
[DragonLoot (by pois1xlive)](https://www.curseforge.com/minecraft/mc-mods/dragonloot)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[Starlight (Fabric) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Eating Animation [Fabric] (by theone_ss)](https://www.curseforge.com/minecraft/mc-mods/eating-animation-fabric)
[Visuality (by PinkGoosik)](https://www.curseforge.com/minecraft/mc-mods/visuality)
[Roughly Enough Items Fabric/Forge (REI) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[More Frogs - Fabric/Quilt/Forge (by frikinjay1)](https://www.curseforge.com/minecraft/mc-mods/more-frogs-fabric)
[GeckoLib (by ThanosGecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Fabric Waystones (by LordDeatHunter)](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones)
[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Better Tridents (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/better-tridents)
[Sodium (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/sodium)
[Fabrication (by unascribed)](https://www.curseforge.com/minecraft/mc-mods/fabrication)
[Skin Layers 3D (Fabric/Forge) (by tr9zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)
[Debugify (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/debugify)
[YUNG's Better Mineshafts (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-fabric)
[TerraBlender (Fabric) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[LambDynamicLights (by LambdAurora)](https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights)
[Interactic (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/interactic)
[oωo (owo-lib) (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/owo-lib)
[Trinkets (Fabric) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/trinkets)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Decorative Blocks (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
[MedievalWeapons (by Globox_Z)](https://www.curseforge.com/minecraft/mc-mods/medievalweapons)
[BCLib (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/bclib)
[FTB Ultimine (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-fabric)
[Emotecraft (Fabric) (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/emotecraft)
[Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
[Konkrete [Fabric] (by Keksuccino)](https://www.curseforge.com/minecraft/mc-mods/konkrete-fabric)
[Grappling Hook :: Restitched (by cloudg360)](https://www.curseforge.com/minecraft/mc-mods/grappling-hook-restitched)
[Beautify: Refabricated (by Suel_ki)](https://www.curseforge.com/minecraft/mc-mods/beautify-refabricated)
[Charm of Undying (Fabric 1.16.1 - 1.19.2) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/charm-of-undying-fabric)
[Spoorn Weapon Attributes [Fabric/Forge] (by spoorn)](https://www.curseforge.com/minecraft/mc-mods/spoorn-weapon-attributes)
[Satin API (by PyrofabTheModsmith)](https://www.curseforge.com/minecraft/mc-mods/satin-api)
[Carpet (by gnembon)](https://www.curseforge.com/minecraft/mc-mods/carpet)
[FTB Library (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric)
[Creeper Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)
[YUNG's Better Nether Fortresses (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses-fabric)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Simply Swords [Fabric & Forge] (by sweenuss)](https://www.curseforge.com/minecraft/mc-mods/simply-swords)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Forge Config API Port [Fabric] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
[MemoryLeakFix (by FX_PR0CESS)](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix)
[Oxidized (by safrodev)](https://www.curseforge.com/minecraft/mc-mods/oxidized)
[Mythic Upgrades [FABRIC] (by trique06)](https://www.curseforge.com/minecraft/mc-mods/mythic-upgrades-fabric)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Macaw's Roofs - Oh The Biomes You'll Go (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs-oh-the-biomes-youll-go)
[Wolf Armor Compat (Fabric) (by evanbones)](https://www.curseforge.com/minecraft/mc-mods/wolf-armor-compat)
[Epic Knights: Shields, Armor and Weapons [Fabric & Forge] (by magistu_)](https://www.curseforge.com/minecraft/mc-mods/epic-knights-armor-and-weapons)
[Culinary Construct (Forge/Fabric) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/culinary-construct)
[YUNG's Better Ocean Monuments (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments-fabric)
[Mod Menu (by ProspectorDev)](https://www.curseforge.com/minecraft/mc-mods/modmenu)
[YDM's Weapon Master (by YourDailyModderx)](https://www.curseforge.com/minecraft/mc-mods/ydms-weapon-master)
[Balm (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm-fabric)
[FallingTree (Forge&Fabric) (by rakambda)](https://www.curseforge.com/minecraft/mc-mods/falling-tree)
[Mandala's GUI - Dark mode (by cesar_zorak)](https://www.curseforge.com/minecraft/texture-packs/mandalas-gui-dark-mode)
[MoreCulling (by FX_PR0CESS)](https://www.curseforge.com/minecraft/mc-mods/moreculling)
[What's That Slot? (by gegybeans)](https://www.curseforge.com/minecraft/mc-mods/whats-that-slot)
[JamLib (by jamalam360)](https://www.curseforge.com/minecraft/mc-mods/jamlib)
[Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[WorldEdit (by sk89q)](https://www.curseforge.com/minecraft/mc-mods/worldedit)
[Illuminations 🔥 (by doctor4t)](https://www.curseforge.com/minecraft/mc-mods/illuminations)
[M.R.U (by itsmineblock11)](https://www.curseforge.com/minecraft/mc-mods/mru)
[Enchanted Vertical Slabs (by Enchanted_Games)](https://www.curseforge.com/minecraft/mc-mods/enchanted-vertical-slabs)
[Deepslate Tweaks (Forge / Fabric) (by SYCO_3)](https://www.curseforge.com/minecraft/mc-mods/deepslate-tweaks)
[BetterEnd (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betterend)
[XP Storage - Trinkets (by sfinc)](https://www.curseforge.com/minecraft/mc-mods/xp-storage-trinkets)
[Macaw's Bridges - Oh The Biomes You'll Go (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-oh-the-biomes-youll-go)
[Auditory (by Sydokiddo)](https://www.curseforge.com/minecraft/mc-mods/auditory)
[Ecologics (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/ecologics)
[Tool Stats (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/tool-stats)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[Charm (by svenhjol)](https://www.curseforge.com/minecraft/mc-mods/charm)
[Carpet-Fixes (by FX_PR0CESS)](https://www.curseforge.com/minecraft/mc-mods/carpet-fixes)
[NetherPortalFix (Fabric Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/netherportalfix-fabric)
[Regrowth (by MacTso)](https://www.curseforge.com/minecraft/mc-mods/regrowth)
[Expanded Weapon Enchanting (by SmushyTaco)](https://www.curseforge.com/minecraft/mc-mods/expanded-weapon-enchanting)
[LazyDFU (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/lazydfu)
[Smooth Boot (Fabric) (by UltimateBoomer)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot)
[Reese's Sodium Options (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)
[Continuity (by Pepper_Bell)](https://www.curseforge.com/minecraft/mc-mods/continuity)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[YUNG's Better Witch Huts (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts-fabric)
[Fabric Seasons (by D4rkness_King)](https://www.curseforge.com/minecraft/mc-mods/fabric-seasons)
[Crawl (Fabric) (by fewizz_)](https://www.curseforge.com/minecraft/mc-mods/crawl)
[Handcrafted (by kekie6)](https://www.curseforge.com/minecraft/mc-mods/handcrafted)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Immersive Weathering [FABRIC] (by OrdanaryMods)](https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-fabric)
[Ambient Environment (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/ambient-environment)
[Tips (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/tips)
[Camera Utils (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/camera-utils)
[Charmonium (by svenhjol)](https://www.curseforge.com/minecraft/mc-mods/charmonium)
[Polymorph (Fabric) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric)
[Macaw's Roofs (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Comforts (Fabric 1.16.5 - 1.19.2) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts-fabric)
[Effective 💦 (by doctor4t)](https://www.curseforge.com/minecraft/mc-mods/effective)
[Macaw's Fences - Oh The Biomes You'll Go (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-oh-the-biomes-youll-go)
[Wolves With Armor (by Draylar1)](https://www.curseforge.com/minecraft/mc-mods/wolves-with-armor)
[Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[More Villagers [Fabric] (by SameDifferent)](https://www.curseforge.com/minecraft/mc-mods/more-villagers-fabric)
[Lithium (Fabric) (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/lithium)
[Easy Anvils [Forge & Fabric] (by Fuzs_)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils)
[Open Parties and Claims (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims)
[XP Storage (by sfinc)](https://www.curseforge.com/minecraft/mc-mods/xp-storage)
[End Goblin Traders (Fabric) (by jab125twitchy)](https://www.curseforge.com/minecraft/mc-mods/end-goblin-traders-fabric)
[Terralith (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/terralith)
[Capybara [Fabric] (by ZestyBlaze)](https://www.curseforge.com/minecraft/mc-mods/capybara-fabric)

**Comment by YaLTeR** [comment]
Hmm, I suspect that mods number 57, 84, 152, and 36th from the bottom might cause issues, but you'll need to double-check.

**Comment by Nimrod108** [comment]
> Hmm, I suspect that mods number 57, 84, 152, and 36th from the bottom might cause issues, but you'll need to double-check.

Thanks for your fast reply, just solved the issue. It's apparently a known conflict with Easy Shulker Boxes, which is planned to be fixed by the mod author in the next update.

**Comment by YaLTeR** [comment]
Ah, that's good to know, thanks.
